version: '2'
services:
  accounts_a:
    image: httpd:alpine
    volumes:
      - ${PWD}/:/usr/local/apache2/htdocs/
    expose:
      - 80
    labels:
      com.widgetshop.service: "accounts"
      com.widgetshop.url: "/accounts/*"
  accounts_b:
    extends: accounts_a

  cart_a:
    image: httpd:alpine
    volumes:
      - ${PWD}/:/usr/local/apache2/htdocs/
    expose:
      - 80
    labels:
      com.widgetshop.service: "cart"
      com.widgetshop.url: "/cart/*"
  cart_b:
    extends: cart_a
  
  catalog_a:
    image: httpd:alpine
    volumes:
      - ${PWD}/:/usr/local/apache2/htdocs/
    expose:
      - 80
    labels:
      com.widgetshop.service: "catalog"
      com.widgetshop.url: "/catalog/*"
  catalog_b:
    extends: catalog_a

  cpx:
    image: cpx:11.1-48.10
    ports:
      - 22
      - 88
      - 80
    tty: true
    privileged: true
