version: '2'

services:
  accounts_a:
    image: httpd:alpine
    volumes:
      - ${PWD}/:/usr/local/apache2/htdocs/
    expose:
      - 80
    labels:
      com.widgetshop.service: "accounts"
      com.widgetshop.url: "/accounts/*"
  accounts_b:
    extends: accounts_a

  cart_a:
    image: httpd:alpine
    volumes:
      - ${PWD}/:/usr/local/apache2/htdocs/
    expose:
      - 80
    labels:
      com.widgetshop.service: "cart"
      com.widgetshop.url: "/cart/*"
  
  catalog_a:
    image: httpd:alpine
    volumes:
      - ${PWD}/:/usr/local/apache2/htdocs/
    expose:
      - 80
    labels:
      com.widgetshop.service: "catalog"
      com.widgetshop.url: "/catalog/*"
  catalog_b:
    extends: catalog_a

  cpx:
    image: store/citrix/netscalercpx:11.1-53.11
    depends_on:
      - catalog_a
      - cart_a
      - accounts_a
    ports:
      - 22
      - 88
      - 80
    tty: true
    privileged: true
    environment:
      - EULA=yes

  automate:
    build: ./automate
    image: automate
    container_name: automate
    depends_on:
      - cpx
      - catalog_b
      - accounts_b
      - cart_a
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"

