version: '2'
services:
  web_a:
    image: httpd:alpine
    expose:
      - 80

  web_b:
    image: httpd:alpine
    links:
      - web_a
    expose:
      - 80
  
  web_c:
    image: httpd:alpine
    links:
      - web_a
      - web_b
    expose:
      - 80
  
  cpx:
    image: store/citrix/netscalercpx:11.1-53.11
    links:
      - web_a
      - web_b
      - web_c
    ports:
      - 22
      - 88
    tty: true
    privileged: true
    environment:
      - EULA=yes
